# Default values for jupyter-notebook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: jupyter/datascience-notebook
  tag: latest
  pullPolicy: IfNotPresent
containerPort: 8888
nameOverride: ""
fullnameOverride: "jupyter-notebook"

service:
  type: NodePort
  port: 8888
  protocol: TCP
  targetPort: 8888

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
  #  - secretName: chart-example-tls
  hosts:
  - jupyter.example.com
  path: /
  servicePort: 8888
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
